### ISSUE TITLE
Message format

### ISSUE THREAD

**Issue by AdmiraalA** [atomy/zabbix-discord#1]
I have set it up according to your instructions 
but i don't get an OK or Error icon

Also the format of the message seems a bit odd : 

Problem:HTTPSserviceisdownonWebserver
Problemstartedat15:41:03on2018.04.06
Problemname:HTTPSserviceisdownonWebserver
Host:Webserver
Severity:Average

OriginalproblemID:69806

**Comment by atomy** [comment]
i think the message format itself comes somewhere from zabbix, what icon did you get instead?

**Comment by AdmiraalA** [comment]
![image](https://user-images.githubusercontent.com/19878820/38466568-7af80cda-3b2b-11e8-8fda-bdf62a559b61.png)

**Comment by atomy** [comment]
I see, your zabbix installation is using "Problem:" and "Resolved:" in the subject line, the script currently only matches to "PROBLEM:" and "OK:" (probably even case sensitive), let me push a fix for that real quick...

**Comment by atomy** [comment]
Can you check if that's working for you? https://github.com/atomy/zabbix-discord/commit/c51672b318ac7b994cae5321913259cc9db60b3c

**Comment by AdmiraalA** [comment]
Seems to work , except for the formatting : 
Problemname:SSHserviceisdownonWebserver

**Comment by atomy** [comment]
Good call, i made a fix so spaces don't get removed https://github.com/atomy/zabbix-discord/commit/a8bd8e56b23a85ded57bf20bf075f0ce9485e610

For the configuration of the message itself you may want to jump to the zabbix config page of *actions*:
![zbx actionx](https://user-images.githubusercontent.com/315285/38467083-8a3c6706-3b33-11e8-8672-edf719144121.png)

**Comment by AdmiraalA** [comment]
Fix works immedialely without me having to edit anything in Zabbix itself :)

**Comment by atomy** [comment]
Awesome!
