### ISSUE TITLE
Zabbix not sending the alert

### ISSUE THREAD

**Issue by nmcc1212** [atomy/zabbix-discord#3]
<img width="1678" alt="Screenshot 2020-10-09 at 09 29 13" src="https://user-images.githubusercontent.com/48334675/95561003-f9680e00-0a11-11eb-8ab8-f847ab8af41d.png">

The test works and shows up

<img width="800" alt="Screenshot 2020-10-09 at 09 31 58" src="https://user-images.githubusercontent.com/48334675/95561206-4cda5c00-0a12-11eb-866a-219775898379.png">
<img width="800" alt="Screenshot 2020-10-09 at 09 31 12" src="https://user-images.githubusercontent.com/48334675/95561211-4e0b8900-0a12-11eb-846e-366a335ac647.png">

**Comment by atomy** [comment]
Thanks for the extensive report.
I assume you are running zabbix 5.x, I myself run "Zabbix 4.0.19 Dockbix XXL" and have never tested it with 5.x. I guess it would be a good thing to update my installation and check the notification-script for compatibility.

However, looking at the docs there doesnt seem to have been any change in that area in Zabbix 5. Can you hover over the Action there and see if that gives you any detailed information? I recall Zabbix supplying some detailed info about errors in that actions area.

![image](https://user-images.githubusercontent.com/315285/95574922-14487b80-0a2e-11eb-85e5-34c6c79434f5.png)

**Comment by atomy** [comment]
Or wait, screw that, that Action will probably just have "Problem created" in it, you are missing the notification action, it is somehow not connected to your Trigger. It should look like this:
![image](https://user-images.githubusercontent.com/315285/95575121-73a68b80-0a2e-11eb-9f87-5dbbcd902e35.png)

**Comment by atomy** [comment]
You may want to check your "Actions"-Configuration, mine is pretty simple and sort of default I guess:
![image](https://user-images.githubusercontent.com/315285/95575302-bc5e4480-0a2e-11eb-905a-caee1abf6674.png)
![image](https://user-images.githubusercontent.com/315285/95575358-dac44000-0a2e-11eb-9f00-276333845bb3.png)

**Comment by nmcc1212** [comment]
Thanks for your help, I narrowed down the problem a bit![image](https://user-images.githubusercontent.com/48334675/95575573-d85de800-0a26-11eb-9336-a70cb3f5893e.png)

Edit: ignore my other tabs, I'm on my phone

**Comment by nmcc1212** [comment]
I still don't know how to fix it though

**Comment by nmcc1212** [comment]
ok, I fixed it by adding the message templates

under media types -> Zabbix-discord -> Message templates 

I just used the default messages

<img width="907" alt="Screenshot 2020-10-09 at 12 49 45" src="https://user-images.githubusercontent.com/48334675/95579679-f67b1680-0a2d-11eb-8c79-e74b1eec0e61.png">
