### ISSUE TITLE
Zabbix not sending alert

### ISSUE THREAD

**Issue by nislab-hslu** [atomy/zabbix-discord#4]
We are using Zabbix 5.0.7.

The Media type test works fine. 

When Alerts appear, get updated or get resolved, they are not being sent to discord. All instructions were followed and also potential fixes in the previous Issues have been tried. 
On the dashboard, there are no "Actions" to be displayed on the event:
![grafik](https://user-images.githubusercontent.com/81571557/112846424-5467ed00-90a6-11eb-863f-1ab1ff85de60.png)

`tail -f /var/log/zabbix/zabbix_server.log` doesn't spit out anything regarding the messaging.

Here some screenies:

![grafik](https://user-images.githubusercontent.com/81571557/112844745-5df05580-90a4-11eb-8e63-9663a80ea054.png)
![grafik](https://user-images.githubusercontent.com/81571557/112844810-6f396200-90a4-11eb-8438-32963ea059b8.png)
![grafik](https://user-images.githubusercontent.com/81571557/112844891-84ae8c00-90a4-11eb-8be4-64f7c2f7c744.png)
![grafik](https://user-images.githubusercontent.com/81571557/112844925-8d9f5d80-90a4-11eb-80ab-be393472cc2e.png)
![grafik](https://user-images.githubusercontent.com/81571557/112845040-ad368600-90a4-11eb-9e3c-dbc36a884214.png)

How do I connect the action (messge discord) to all my triggers? (if that might pose a issue)
Anybody else got it working on 5.0.7?

**Comment by atomy** [comment]
Well, I am still on 4.x. Your configuration looks good to me.
Maybe try to add the media to an administrator account, dunno if read-only permission only is limiting that whole thing from working.
![image](https://user-images.githubusercontent.com/315285/112847903-d3115a00-90a7-11eb-87dd-22f5587592cf.png)

If the script itself were faulty, you would usually see that zabbix attempted to execute the action and it errored. In your case it seems that it doesnt even try to run it.

**Comment by nislab-hslu** [comment]
Thank you for the fast answer! 

Unfortunately, even with full admin access over all groups nothing changes.

Exactly, for some reason, it wouldn't even try running the script upon trigger. I also tried assigning the Media type to the super admin, to see if it would execute then, but no change. No error in the log.

And as mentioned before, even Action based operations won't do the trick.

**Comment by rileyjnevins** [comment]
Having the same issue here.

**Comment by nislab-hslu** [comment]
We were able to resolve the problem. We are not sure what did the trick. We were installing updates and rebooting the system and reassigning super administrator rights to the discord user. Our current Zabbix version: 5.2.6.

@rileyjnevins were you able to solve your problem and  can i close the issue?

**Comment by atomy** [comment]
I am also in the process of upgrading my zabbix installation to 5.4 to see if that affects the script from working.

**Comment by rileyjnevins** [comment]
I’ve actually got this working a while back, made a public repo on my account.

**Comment by atomy** [comment]
I completed uprading my installation to 5.4, the script still works. I just had to add curl and python to my zabbix-docker-container.

Good to know that there's also a yaml-version on the official-site to probably achieve the same :+1:
